[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

build_flags = 
    -std=gnu++17
    -Ilib/Controle
    -Ilib/Filtros
    -Ilib/Telemetria
    -Ilib/Sensores_Pista
    -Ilib/Sensores_Motor

build_unflags = -std=gnu++11

lib_deps =
    bblanchon/ArduinoJson @ ^7.4.3
    knolleary/PubSubClient @ ^2.8 
    marcoschwartz/LiquidCrystal_I2C @ ^1.1.4
    mikalhart/TinyGPSPlus @ ^1.0.3


lib_ldf_mode = deep+